{{- if and .Values.enabled .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .name }}
    {{- if eq .type "dockerconfigjson" }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{`{{ .username }}`}}",
                "password": "{{`{{ .password }}`}}",
                "auth": "{{`{{ printf "%s:%s" .username .password | b64enc }}`}}"
              }
            }
          }
    {{- end }}
  data:
    {{- if eq .type "dockerconfigjson" }}
    - secretKey: username
      remoteRef:
        key: {{ .key }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .key }}
        property: password
    {{- else }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .key }}
    {{- end }}
{{- end }}
{{- end }}
