{{- if and .Values.enabled .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.serviceAccountName }}@{{ .Values.workloadIdentity.projectId }}.iam.gserviceaccount.com
    iam.gke.io/return-principal-id-as-email: "true"
{{- end }}
